name: Manual Release

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment for release'
        required: true
        default: 'production'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Release to AWS
        run: ./your-release-script.sh ${{ github.event.inputs.environment }}
