on:
  push:
    branches:
      - main
jobs:
   build: 
     runs-on: ubuntu-latest
     steps: 
      - uses: actions/checkout@v2
        with: 
          fetch-depth: 0
      - name: get file changes
        run: | 
          git diff --name-only ${{ github.event.before }} ${{ github.event.after }}
      - name: Check commit messages
        run: git log --format=%B ${{ github.event.before }}..${{ github.event.after }}
