on:
  push:
    branches:
      - main
jobs:
   build: 
     runs-on: ubuntu-latest
     steps: 
      - uses: actions/checkout@v2
        with: 
          fetch-depth: 0
      - name: Check commit messages
        run: git log --format=%B ${{ github.event.before }}..${{ github.event.after }}
      - name: print 1
        run: git log --format=%B ${{ github.event.before }}..${{ github.event.after }} | grep -E -i '^(feat|fix)|!'
      - name: print 2
        run: git log --format=%B ${{ github.event.before }}..${{ github.event.after }} | grep -E -i '^(feat|fix)|!' | | wc -l