name: Check Commit Messages

on:
  push:
    branches:
      - main

jobs:
  check-commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check commit messages
        run: |
          git log --format=%B (git rev-list -n 1 HEAD..$GITHUB_SHA)
          git log --format=%B (git rev-list -n 1 HEAD..$GITHUB_SHA) | grep -E -i '^(feat|fix)|!'
