on:
  push:
    branches:
      - main
jobs:
   build: 
     runs-on: ubuntu-latest
     steps: 
      - uses: actions/checkout@v2
        with: 
          fetch-depth: 0
      - name: Check commit messages
        run: |
          echo "git log --format=%B ${{ github.event.before }}..${{ github.event.after }}"
          echo "git log --format=%B ${{ github.event.before }}..${{ github.event.after }} | grep -E -i '^(feat|fix)|!'"
          echo "git log --format=%B ${{ github.event.before }}..${{ github.event.after }} | grep -E -i '^(feat|fix)|!' | | wc -l"